zebpay.url=https://www.zebapi.com/pro/v1/market/
usdinr=72.91
coinMarket.url=https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest
api.key=X-CMC_PRO_API_KEY
apiKey.value=ca82062d-c70f-4eaf-997d-c4e995fb458a